### ISSUE TITLE
lack of CONTRIBUTING.md

### ISSUE THREAD

**Issue by ohAitch** [urbit/sample-apps#11]
Relatedly, the unix sync instructions used to maintain(/mirror) wactex-ribmex should _also_ live in this repository, but are only currently accessible in history.

**Comment by juped** [comment]
That's like putting the continuity breach instructions on the main contributing.md. Pls keep internal corporate procedures internal (not that there's any big secrets in that one, but it's not the right place)

**Comment by ohAitch** [comment]
I say CONTRIBUTING because the main purpose of this would be setting up
fakezods with an example desk, which are necessary for the
(breachy) development of e.g. apps. But sure, my main point is this should
be recorded /somewhere/.
