### ISSUE TITLE
Adapt web examples

### ISSUE THREAD

**Issue by galenwp** [urbit/sample-apps#13]
Without `hymn.hook`s many of the ford examples are irrelevant.  The `%g` examples probably have to be restructured.

**Comment by ohAitch** [comment]
Can't they be move to web/app, or for that matter be restructured as tree
modules? Something doesn't actually need to be a ~module~ to be loaded by
the hook-ish facility in ren/tree.

**Comment by galenwp** [comment]
Either could work, yeah.  But something has to happen.  Could be done by a savvy contributor.

**Comment by galenwp** [comment]
@zaphar this could be a good way to understand some of the new web stuff ; )

**Comment by galenwp** [comment]
With https://github.com/urbit/examples/commit/e5f18ff0a96681778e94dc114648e226212ce5f5 this is done, except for 12.

**Comment by galenwp** [comment]
@ohAitch could you take a look at 12?  I think this also requires your change to `ren/urb`

**Comment by galenwp** [comment]
You may need my https://github.com/galenwp/arvo/tree/ren-change to see the difference.  I committed your change to the urb renderer there, but I changed `app` to `static`.  Up for discussion about that, but think `static` is more descriptive of what's going to go in there.

**Comment by ohAitch** [comment]
`app` is a bad name if we're not using it for frontends, yeah, but `static`
seems to be kind of the opposite of what it's doing. `page` maybe?

**Comment by zaphar** [comment]
Sweet!

**Comment by galenwp** [comment]
I was thinking like "static pages", but I guess they could be not-static.  What's the opposite of a tree?  A root?  That's a terrible name too...

**Comment by ohAitch** [comment]
The ford examples are like "the result of adding 2 and 2 by
dynamically executing hoon is {<(add 2 2)>}", yeah. And the ren/urb change
that stops the hoon files as static source code listings prevents you from
loading any other static resources either.

/web/run maybe?

**Comment by ohAitch** [comment]
Ah, the main problem is "load resources by number" is no longer a ford
rune. _fits a filter into the /;_

**Comment by galenwp** [comment]
@ohAitch did that filter get fit in with a commit, or are we waiting for the horn change?

**Comment by ohAitch** [comment]
It did with 1854e0e, but I want to do the horn change urbit/arvo#34 before formally
closing this.

**Comment by galenwp** [comment]
OK sounds good.
