### ISSUE TITLE
:examples-sink and :examples-source are broken

### ISSUE THREAD

**Issue by ault011** [urbit/sample-apps#20]
Something’s wrong with the subscription between both the :examples-sink and :examples-source apps; I assume their types are messed up after some update. 

Check out: http://urbit.org/docs/arvo/subscriptions/ for more detailed instructions on how to use/understand the two apps. 

Here's the error i got after having started both apps:

```
activated app home/examples-source
[%subscribed-to pax=/sole]
> |start %examples-source
>=
[linked to [p=~mictyd-banlur q=%examples-source]]
; ~doznec is ok
[unlinked from [p=~mictyd-banlur q=%examples-source]]
gall: %examples-source: no poke arm for sole-action
[%drum-coup-fail ~mictyd-banlur 1 p=~mictyd-banlur q=%examples-source]
    activated app home/examples-sink
> |start %examples-sink
>=
> :examples-source 7
>=
```

**Comment by hoclun-rigsep** [comment]
Yeah, looks like there's a mark &sole-action and %dill or %dojo or some damn thing is poking this app with one. But I don't know why this app gets poked thus and a "hello,world" app doesn't. I am investigating. 

Is there some way to reset %gall to a fresh state?

**Comment by philipcmonk** [comment]
&sole-action's get poked if it thinks you have a linked console connection
(like solo and talk do). It automatically links a console connection if you
accept a peer along a particular path (/console maybe?). Anyhow,
:examples-source has a ++peer, so it accepts peers along _any_ path. If you
specialize the ++peer (for example, to ++peer-the-path), it should stop
trying to link a console.

**Comment by hoclun-rigsep** [comment]
Ok. Once I understand this I will fix the example and the corresponding documentation. I'm having trouble investigating though because once I start the app I can't reproduce the error—`|start %source` just tells me it's already started.

**Comment by ault011** [comment]
Any luck/progress on this, hidwes?

**Comment by hoclun-rigsep** [comment]
Yeah I'm looking at it again after being afk for a week. It would be great to have comprehensive documentation about what names are special to %gall and whatever handles +generators.

**Comment by ohAitch** [comment]
"Names special to gall" as in arm names? `poke-*`/`coup`, `peek-*`/`peer-*`/`reap`, and `prep` are the common ones, in general anything that is or starts with a four-letter word and(usually) isn't called from other arms in the app.

More exhaustively,

```
➤ grep ap-find arvo/gall.hoon 
      =+  cug=(ap-find %peek ren tyl)
      =+  cug=(ap-find [%diff p.cag +.pax])
    ++  ap-find                                         ::  general arm
      =+  cug=(ap-find %peer pax)
      =+  cug=(ap-find %poke p.cag ~)
      =+  cug=(ap-find /lame)
      =+  cug=(ap-find [-.q.vax pax])
      =+  cug=(ap-find [wha p.cag pax])
      =+  cug=(ap-find %pull q.u.wim)
      =+  cug=(ap-find cog pax)
➤ grep ap-take arvo/gall.hoon 
        $coup  (ap-take q.q.pry %coup +.pax `!>(p.cuf))
        $quit  (ap-take q.q.pry %quit +.pax ~)
        $reap  (ap-take q.q.pry %reap +.pax `!>(p.cuf))
    ++  ap-take                                         ::  non-diff gall take
        ::  ~&  [%ap-take-none cog pax]
```

yields `%peer %poke %lame %pull` directly(incoming requests), `%coup %quit %reap` by reference to `ap-take`(responses to outgoing gall request), and the tag of any `sign-arvo`(see `gift-*` in zuse) that would be given in response to the cards whitelisted in `++ap-vain` or handled in `++ap-move`.

**Comment by ohAitch** [comment]
All of this ofc belongs in the gall doc, and preferably also in a hoon type somewhere.

Generators are comparatively simple: `:dojo` looks for a `%say`/`%ask`/`%get` tag, and expects a gate that produces a mark-tagged noun / dialog which eventually produces a marked noun / web scraper also producing one, respectively. As far as interacting with gall, this just manifests as a `++poke`; any call to `.^(foo %g /=appname=/...)` will `peek` and on `~` proceed to `peer`, but this is technically a general ford feature, and is also usable in e.g. dojo.

**Comment by hoclun-rigsep** [comment]
`++peer-the-path` looked too much like an English imperative sentence, like we were 'peering' something called 'the path.'
